//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraper.Scraper.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuisnessHeadLine
    {
        public System.DateTime PublishedDate { get; set; }
        public string NewsSource { get; set; }
        public string Url { get; set; }
        public string Heading { get; set; }
        public string ContentBrief { get; set; }
    }
}
